CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    email VARCHAR(50),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB AUTO_INCREMENT = 1;

CHANGE MASTER TO MASTER_HOST = 'master-1',
MASTER_USER = 'replicate',
MASTER_PASSWORD = 'password',
MASTER_AUTO_POSITION = 1 FOR CHANNEL 'master-1';

CHANGE MASTER TO MASTER_HOST = 'master-2',
MASTER_USER = 'replicate',
MASTER_PASSWORD = 'password',
MASTER_AUTO_POSITION = 1 FOR CHANNEL 'master-2';

START SLAVE FOR CHANNEL 'master-1';

START SLAVE FOR CHANNEL 'master-2';